# Generated by Django 3.1.7 on 2021-03-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="text",
            field=models.TextField(default="Text", verbose_name="Type your article"),
        ),
    ]
