# Generated by Django 3.1.7 on 2021-03-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210313_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='amount_upvotes',
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True),
        ),
    ]
